# Generated by Django 5.2 on 2025-04-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_number_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='content',
        ),
    ]
