# Generated by Django 5.2 on 2025-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Language', 'Language'), ('Technology', 'Technology'), ('Course', 'Course'), ('Database', 'Database')], max_length=20)),
            ],
        ),
    ]
